#!/usr/bin/env bash
# =============================================================================
# setup.sh - One-time environment preparation for the "meco smp" PaperMC
# server on GitHub Codespaces (4 vCPU / 16GB RAM) + Playit.gg static tunnel.
#
# Optional env vars (Codespaces secrets):
#   GH_PAT          - GitHub PAT (ghp_...) for `gh` CLI auth (optional)
#   PLAYIT_SECRET   - playit.gg agent secret for unattended re-linking
#                     (get it from playit.gg dashboard after first claim)
#
# Runtime overrides (optional):
#   MC_VERSION      - Minecraft version to fetch PaperMC for (default 1.21.1)
# =============================================================================
set -euo pipefail

MC_VERSION="${MC_VERSION:-1.21.1}"
PAPER_API="https://api.papermc.io/v2/projects/paper"
PLAYIT_URL="https://github.com/playit-cloud/playit-agent/releases/latest/download/playit-linux-x86_64"

echo "==> [1/6] Updating system packages..."
sudo apt-get update
sudo apt-get install -y curl jq wget unzip tar gnupg openjdk-21-jre-headless

echo "==> [2/6] Installing Playit.gg agent (linux-x86_64)..."
if ! command -v playit >/dev/null 2>&1; then
  curl -sL "${PLAYIT_URL}" -o playit
  chmod +x playit
  sudo mv playit /usr/local/bin/playit
fi
playit --version || true

echo "==> [3/6] Pre-linking playit agent with stored secret (if provided)..."
if [ -n "${PLAYIT_SECRET:-}" ]; then
  # Non-interactive link so fresh containers skip the claim-link step.
  mkdir -p "${HOME}/.config/playit"
  printf '{"agent_secret":"%s"}' "${PLAYIT_SECRET}" > "${HOME}/.config/playit/agent.json"
  echo "      Secret stored in ~/.config/playit/agent.json"
else
  echo "      No PLAYIT_SECRET - first run of start.sh will print a Claim Link."
fi

echo "==> [4/6] Fetching latest PaperMC build for Minecraft ${MC_VERSION}..."
PAPER_BUILD=$(curl -s "${PAPER_API}/versions/${MC_VERSION}/builds" \
  | jq -r '.builds[-1].build' 2>/dev/null || true)
if [ -z "${PAPER_BUILD}" ] || [ "${PAPER_BUILD}" = "null" ]; then
  echo "ERROR: No PaperMC build found for version ${MC_VERSION}."
  echo "       Override with:  MC_VERSION=1.21.4 bash setup.sh"
  exit 1
fi
PAPER_JAR=$(curl -s "${PAPER_API}/versions/${MC_VERSION}/builds/${PAPER_BUILD}" \
  | jq -r '.downloads.application.name')
curl -sL -o server.jar \
  "${PAPER_API}/versions/${MC_VERSION}/builds/${PAPER_BUILD}/downloads/${PAPER_JAR}"
echo "      Downloaded: ${PAPER_JAR} (build ${PAPER_BUILD})"

echo "==> [5/6] Writing eula.txt and server.properties..."
echo "eula=true" > eula.txt

cat > server.properties <<'EOF'
# --- Generated by setup.sh (meco smp) ---
# motd uses \u00A7 (= §) color codes: gold+bold name, gray divider, green tag.
online-mode=false
motd=\u00A76\u00A7lWelcome to meco smp \u00A77| \u00A7a24/7 Playit.gg Hosted
server-port=25565
difficulty=normal
gamemode=survival
max-players=20
view-distance=10
simulation-distance=10
spawn-protection=16
enable-command-block=true
level-name=world
pvp=true
white-list=false
EOF

echo "==> [6/6] Configuring GitHub CLI..."
if [ -n "${GH_PAT:-}" ]; then
  echo "${GH_PAT}" | gh auth login --with-token
  gh auth status
else
  echo "      GH_PAT not set - skipping gh authentication (optional)."
fi

echo ""
echo "Setup complete."
echo "Start the server and tunnel with:  bash start.sh"
